[package]
name = "kazama"
version = "0.1.0"
authors = ["spirizeon"]
license = "MIT"
license-file = "LICENSE"
keywords = ["ollama","wrapper"]
categories = ["command-line-utilities"]


[dependencies]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
